import type { Metadata } from "next";
import "@/styles/globals.css";
import { ParticleBackground } from "@/components/client/ParticleBackground";
import Blob from "@/components/Blob";
import Navbar from "@/components/server/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-dark relative overflow-hidden">
          <Blob />
          <ParticleBackground />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
